### ISSUE TITLE
UTF8 issue

### ISSUE THREAD

**Issue by sacuba** [rodhoward/node-sybase#12]
i met an issue when my table got utf8 content. 
      throw er; // Unhandled 'error' event
      ^
Error: Invalid JSON (Invalid UTF-8 character at position 10312 in state STRING1)
    at Parser.proto.write (C:\work\git\CCS\migration\node_modules\jsonparse\jsonparse.js:171:31)
    at Stream.<anonymous> (C:\work\git\CCS\migration\node_modules\JSONStream\index.js:23:12)
    at Stream.stream.write (C:\work\git\CCS\migration\node_modules\through\index.js:26:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)

**Comment by rodhoward** [comment]
I have accepted a pull request that might fix this issue.  Basically it sets the encoding on the output stream to be UTF8.  Please let me know if that solves your problem as I have no way to test anymore I have moved on from Sybase!!!

**Comment by sacuba** [comment]
it did fix my issue. Thank you very much!
