### ISSUE TITLE
Error: Exception in thread "main": 

### ISSUE THREAD

**Issue by averri** [rodhoward/node-sybase#30]
Running the following code:

```javascript
const Sybase = require('sybase')
const db = new Sybase('test-server', 2640, 'test-db', 'user1', 'pass1')

db.connect(function (err) {
  if (err) return console.log(err)
  db.query('select * from user where user_id = 42', function (err, data) {
    if (err) console.log(err)
    console.log(data)
    db.disconnect()
  })
})
```

... throws the exception:

```
Error: Exception in thread "main" 
    at Socket.<anonymous> (node_modules\sybase\src\SybaseDB.js:62:15)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:273:9)
    at Socket.Readable.push (_stream_readable.js:214:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

I'm running Node v13.11.0 on Windows 10.

**Comment by averri** [comment]
The issue has been fixed after dropping the `lib` folder under `dist` folder.

**Comment by trisaputra1997** [comment]
Hi @averri ,
May I know that, which path that you need to drop/delete `lib` folder under `dist` folder
